# Title and subheading for your site. Used on the home page and in page
# titles.
#
title: "RubyOps.net"
subtitle: "Lessons learned, code written, hacks, etc."

# You should really specify your content's author when generating an
# Atom feed. Specify at least one of name, uri or email, and Nesta will
# include it in your feed. See the Atom spec for more info:
#
# http://www.atomenabled.org/developers/syndication/atom-format-spec.php#element.feed
#
author:
  name: Joshua P. Mervine
  uri: http://www.rubyops.net/
  email: joshua@mervine.net

# You can stick with the default look and feel, or use a theme. Themes are
# easy to create or install, and live inside the themes directory. You
# can also use scripts/theme to install them.
#
theme: rubyops

disqus_short_name: rubyops

# cache
#     Set it to true if you'd like Nesta to cache your pages in ./public.
#     Useful if you're deploying Nesta with a proxy server such as Nginx,
#     but not in the least bit helpful if your pages are dynamic, or you're
#     deploying Nesta to Heroku.
#
cache: false

content: content

google_analytics_code: "UA-32343843-1"

#google_ad:
  #client: "ca-pub-1003846054569915"
  #slot: "5207675864"
  #width: 200
  #height: 200

  #client: "ca-pub-1003846054569915"
  #slot:   "8763415799"
  #width:  728
  #height: 90

sharethis: "80df436a-9769-4c43-a468-adcd0ae6ec70"

#sharethis_buttons: # optional
#- :twitter
#- :linkedin
#- :reddit
#- :digg
#- :facebook_like


production:
  diskcached: true # default
  diskcached_timeout: 3600 # default (in seconds)

